### ISSUE TITLE
Search query urls log stays empty

### ISSUE THREAD

**Issue by PabiGamito** [PabiGamito/future#4]
In background.js even after loading a search page, SearchQueryUrls = [].
This means it is not being successfully updated with all links from a search page.
app.js never sends a request to log links from a search.

**Comment by PabiGamito** [comment]
In app.js getting error:

```
Error in event handler for (unknown): ReferenceError: _ is not defined
    at HTMLAnchorElement.<anonymous> (chrome-extension://dcibffeidjhnkcpkinoaecefmhhndngo/src/js/app.js:40:12)
    at Function.each (chrome-extension://dcibffeidjhnkcpkinoaecefmhhndngo/src/libs/jquery.min.js:2:2815)
    at r.each (chrome-extension://dcibffeidjhnkcpkinoaecefmhhndngo/src/libs/jquery.min.js:2:1003)
    at chrome-extension://dcibffeidjhnkcpkinoaecefmhhndngo/src/js/app.js:37:14
```

It seems like this is where it breaks and why search query links never get to the background to be logged.

**Comment by PabiGamito** [comment]
_.isEmpty(link) seems to be what broke the code, replaced with !link and links are now logged successfully. Request to log links is being sent, but with empty links array. It seems like it's because data is not successfully being pushed in the SearchQueryUrls array in app.js even though no error arises.

**Comment by PabiGamito** [comment]
url = $(value).attr('data-href') = undefined even though $(value).text() returns the title of the link. So url = undefined might be causing a problem

**Comment by PabiGamito** [comment]
Apparently, $(value) does not return the data-href attribute it has in html for some reason it becomes a simple href attribute. So adding

```
 if (!url) {
          url = $(value).attr('href')
        }
```

fixes it.
